# Generated by Django 6.0.7 on 2026-08-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID цены в Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID продукта в Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии в Stripe'),
        ),
    ]
